FROM debian:buster
MAINTAINER orsay0827@gmail.com

RUN apt-get -y update
RUN apt-get install -y build-essential libatomic-ops-dev libatlas3-base \
        libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev \
        libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev \
        libopenblas-dev libblas-dev libopenjp2-7 m4 cmake tk-dev python3 cython \
        python3-dev python3-yaml python3-setuptools python3-pip git libjpeg-dev \
        zlib1g-dev libfreetype6-dev liblcms-dev libopenjp2-7 libtiff5

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --user --upgrade pyserial

WORKDIR /root
RUN git clone --recursive https://github.com/pytorch/pytorch

WORKDIR /root/pytorch
RUN git submodule sync
RUN git submodule update --init --recursive

RUN export USE_CUDA=0
RUN export USE_DISTRIBUTED=0
RUN export USE_MKLDNN=0
RUN export USE_NNPACK=1
RUN export USE_QNNPACK=1

RUN python3 -m pip install --user --upgrade -r requirements.txt
RUN python3 setup.py build
RUN python3 setup.py install

RUN python3 -m pip install --user --upgrade torchvision
RUN python3 -m pip install --user pillow==6.1

WORKDIR /root
RUN wget https://www.piwheels.org/simple/scipy/scipy-1.3.3-cp37-cp37m-linux_armv7l.whl
RUN wget https://www.piwheels.org/simple/scikit-learn/scikit_learn-0.22.1-cp37-cp37m-linux_armv7l.whl
RUN python3 -m pip install --user scipy-1.3.3-cp37-cp37m-linux_armv7l.whl scikit_learn-0.22.1-cp37-cp37m-linux_armv7l.whl

RUN rm -rf pytorch
RUN rm -rf scipy-1.3.3-cp37-cp37m-linux_armv7l.whl
RUN rm -rf scikit_learn-0.22.1-cp37-cp37m-linux_armv7l.whl
